"use client";

import React, { useRef, useEffect } from "react";
import { Upload, X, Image as ImageIcon, Sparkles } from "lucide-react";
import { toast } from "sonner";

export interface StoreBrandingUploadProps {
  /**
   * Temporary preview URL (blob: or existing string) for the store logo
   */
  logoPreview?: string | null;
  /**
   * Temporary preview URL (blob: or existing string) for the store banner
   */
  bannerPreview?: string | null;
  /**
   * Callback when a logo file is selected or removed.
   * Passes the File object for post-creation upload, and the object URL for instant preview.
   */
  onLogoSelect?: (file: File | null, previewUrl: string) => void;
  /**
   * Callback when a banner file is selected or removed.
   * Passes the File object for post-creation upload, and the object URL for instant preview.
   */
  onBannerSelect?: (file: File | null, previewUrl: string) => void;
  /**
   * Legacy props for backward compatibility
   */
  logoUrl?: string;
  bannerUrl?: string;
  onLogoChange?: (url: string, publicId?: string) => void;
  onBannerChange?: (url: string, publicId?: string) => void;
  disabled?: boolean;
}

const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
const ALLOWED_MIME_TYPES = ["image/jpeg", "image/png", "image/webp"];

export function StoreBrandingUpload({
  logoPreview,
  bannerPreview,
  onLogoSelect,
  onBannerSelect,
  logoUrl,
  bannerUrl,
  onLogoChange,
  onBannerChange,
  disabled = false,
}: StoreBrandingUploadProps) {
  const logoInputRef = useRef<HTMLInputElement | null>(null);
  const bannerInputRef = useRef<HTMLInputElement | null>(null);

  // Track active blob URLs generated by URL.createObjectURL to prevent memory leaks
  const activeBlobUrlsRef = useRef<Set<string>>(new Set());

  // Revoke all created blob URLs on unmount
  useEffect(() => {
    const urls = activeBlobUrlsRef.current;
    return () => {
      urls.forEach((url) => {
        if (url.startsWith("blob:")) {
          URL.revokeObjectURL(url);
        }
      });
      urls.clear();
    };
  }, []);

  const revokeBlobUrl = (url?: string | null) => {
    if (url && url.startsWith("blob:") && activeBlobUrlsRef.current.has(url)) {
      URL.revokeObjectURL(url);
      activeBlobUrlsRef.current.delete(url);
    }
  };

  const createPreview = (file: File): string => {
    const previewUrl = URL.createObjectURL(file);
    activeBlobUrlsRef.current.add(previewUrl);
    return previewUrl;
  };

  // Resolved display URLs (prioritize current preview over initial stored URL)
  const currentLogoDisplay = logoPreview ?? logoUrl ?? "";
  const currentBannerDisplay = bannerPreview ?? bannerUrl ?? "";

  const handleLogoFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate file type
    if (
      !file.type.startsWith("image/") &&
      !ALLOWED_MIME_TYPES.includes(file.type)
    ) {
      toast.error("Invalid file format", {
        description: "Please select a valid image file (PNG, JPG, WEBP).",
      });
      if (logoInputRef.current) logoInputRef.current.value = "";
      return;
    }

    // Validate file size
    if (file.size > MAX_FILE_SIZE) {
      toast.error("File size too large", {
        description: "Logo image size cannot exceed 5MB.",
      });
      if (logoInputRef.current) logoInputRef.current.value = "";
      return;
    }

    // Revoke previous blob preview if any
    revokeBlobUrl(logoPreview);

    // Generate instant client-side preview URL without server upload
    const previewUrl = createPreview(file);

    if (onLogoSelect) {
      onLogoSelect(file, previewUrl);
    }
    if (onLogoChange) {
      onLogoChange(previewUrl, "");
    }

    toast.info("Logo preview selected (will upload after store creation)");

    if (logoInputRef.current) {
      logoInputRef.current.value = "";
    }
  };

  const handleRemoveLogo = () => {
    revokeBlobUrl(logoPreview);
    if (onLogoSelect) {
      onLogoSelect(null, "");
    }
    if (onLogoChange) {
      onLogoChange("", "");
    }
    if (logoInputRef.current) {
      logoInputRef.current.value = "";
    }
  };

  const handleBannerFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate file type
    if (
      !file.type.startsWith("image/") &&
      !ALLOWED_MIME_TYPES.includes(file.type)
    ) {
      toast.error("Invalid file format", {
        description: "Please select a valid image file (PNG, JPG, WEBP).",
      });
      if (bannerInputRef.current) bannerInputRef.current.value = "";
      return;
    }

    // Validate file size
    if (file.size > MAX_FILE_SIZE) {
      toast.error("File size too large", {
        description: "Banner image size cannot exceed 5MB.",
      });
      if (bannerInputRef.current) bannerInputRef.current.value = "";
      return;
    }

    // Revoke previous blob preview if any
    revokeBlobUrl(bannerPreview);

    // Generate instant client-side preview URL without server upload
    const previewUrl = createPreview(file);

    if (onBannerSelect) {
      onBannerSelect(file, previewUrl);
    }
    if (onBannerChange) {
      onBannerChange(previewUrl, "");
    }

    toast.info("Banner preview selected (will upload after store creation)");

    if (bannerInputRef.current) {
      bannerInputRef.current.value = "";
    }
  };

  const handleRemoveBanner = () => {
    revokeBlobUrl(bannerPreview);
    if (onBannerSelect) {
      onBannerSelect(null, "");
    }
    if (onBannerChange) {
      onBannerChange("", "");
    }
    if (bannerInputRef.current) {
      bannerInputRef.current.value = "";
    }
  };

  return (
    <div className="space-y-4">
      {/* Section Header */}
      <div className="flex items-center justify-between">
        <label className="flex items-center gap-1.5 text-xs font-semibold text-[#0F172A]">
          <Sparkles className="size-3.5 text-[#7C5CFC]" />
          <span>Store Branding</span>
          <span className="text-[11px] font-normal text-[#64748B]">
            (Optional)
          </span>
        </label>
        <span className="text-[11px] text-[#64748B]">Logo & Banner</span>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {/* Store Logo Card */}
        <div className="rounded-xl border border-[#E2E8F0] bg-[#F8FAFC]/50 p-3.5 space-y-2.5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-[#1E293B]">
              Store Logo
            </span>
            <span className="text-[10px] text-[#64748B]">1:1 ratio</span>
          </div>

          <div className="flex items-center gap-3">
            {/* Logo Preview Box */}
            <div className="relative flex size-14 shrink-0 items-center justify-center rounded-xl border border-dashed border-[#CBD5E1] bg-white overflow-hidden shadow-2xs">
              {currentLogoDisplay ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={currentLogoDisplay}
                  alt="Store logo preview"
                  className="size-full object-contain p-1"
                />
              ) : (
                <ImageIcon className="size-5 text-[#94A3B8]" />
              )}
            </div>

            {/* Logo Actions */}
            <div className="flex flex-col gap-1.5">
              <input
                ref={logoInputRef}
                type="file"
                accept="image/jpeg,image/png,image/webp"
                disabled={disabled}
                onChange={handleLogoFileChange}
                className="hidden"
                id="storeLogoInput"
              />
              <div className="flex items-center gap-2">
                <label
                  htmlFor="storeLogoInput"
                  className={`inline-flex items-center gap-1.5 rounded-full border border-[#E2E8F0] bg-white px-3 py-1.5 text-xs font-semibold text-[#0F172A] hover:bg-[#F8F9FC] shadow-2xs transition-colors ${
                    disabled
                      ? "opacity-60 cursor-not-allowed"
                      : "cursor-pointer"
                  }`}
                >
                  <Upload className="size-3 text-[#7C5CFC]" />
                  <span>{currentLogoDisplay ? "Change" : "Upload"}</span>
                </label>

                {currentLogoDisplay && !disabled && (
                  <button
                    type="button"
                    onClick={handleRemoveLogo}
                    className="rounded-full p-1.5 text-[#64748B] hover:text-red-600 hover:bg-red-50 transition-colors cursor-pointer"
                    title="Remove logo"
                  >
                    <X className="size-3.5" />
                  </button>
                )}
              </div>
              <p className="text-[10px] text-[#64748B]">
                PNG, JPG or WEBP up to 5MB
              </p>
            </div>
          </div>
        </div>

        {/* Store Banner Card */}
        <div className="rounded-xl border border-[#E2E8F0] bg-[#F8FAFC]/50 p-3.5 space-y-2.5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-[#1E293B]">
              Store Banner
            </span>
            <span className="text-[10px] text-[#64748B]">
              16:9 or 3:1 ratio
            </span>
          </div>

          <div className="flex items-center gap-3">
            {/* Banner Preview Box */}
            <div className="relative flex h-14 w-24 shrink-0 items-center justify-center rounded-xl border border-dashed border-[#CBD5E1] bg-white overflow-hidden shadow-2xs">
              {currentBannerDisplay ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={currentBannerDisplay}
                  alt="Store banner preview"
                  className="size-full object-cover"
                />
              ) : (
                <ImageIcon className="size-5 text-[#94A3B8]" />
              )}
            </div>

            {/* Banner Actions */}
            <div className="flex flex-col gap-1.5">
              <input
                ref={bannerInputRef}
                type="file"
                accept="image/jpeg,image/png,image/webp"
                disabled={disabled}
                onChange={handleBannerFileChange}
                className="hidden"
                id="storeBannerInput"
              />
              <div className="flex items-center gap-2">
                <label
                  htmlFor="storeBannerInput"
                  className={`inline-flex items-center gap-1.5 rounded-full border border-[#E2E8F0] bg-white px-3 py-1.5 text-xs font-semibold text-[#0F172A] hover:bg-[#F8F9FC] shadow-2xs transition-colors ${
                    disabled
                      ? "opacity-60 cursor-not-allowed"
                      : "cursor-pointer"
                  }`}
                >
                  <Upload className="size-3 text-[#7C5CFC]" />
                  <span>{currentBannerDisplay ? "Change" : "Upload"}</span>
                </label>

                {currentBannerDisplay && !disabled && (
                  <button
                    type="button"
                    onClick={handleRemoveBanner}
                    className="rounded-full p-1.5 text-[#64748B] hover:text-red-600 hover:bg-red-50 transition-colors cursor-pointer"
                    title="Remove banner"
                  >
                    <X className="size-3.5" />
                  </button>
                )}
              </div>
              <p className="text-[10px] text-[#64748B]">
                Wide header cover image
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
