import type { RecentOrderItem } from "../../types/stores.types";

export const FALLBACK_RECENT_ORDERS: RecentOrderItem[] = [
  {
    id: "ord-1",
    orderNumber: "#SD-4821",
    invoiceNo: "#SD-4821",
    customer: {
      id: "c1",
      name: "Tanvir Ahmed",
      email: "tanvir@gmail.com",
      phone: null,
    },
    paymentStatus: "PAID",
    paymentBadge: "Paid",
    orderStatus: "COMPLETED",
    date: "Sep 15, 2026",
    createdAt: "2026-09-15T10:00:00Z",
    amount: 3200,
    formattedAmount: "৳3,200",
  },
  {
    id: "ord-2",
    orderNumber: "#SD-4820",
    invoiceNo: "#SD-4820",
    customer: {
      id: "c2",
      name: "Nusrat Jahan",
      email: "nusrat@yahoo.com",
      phone: null,
    },
    paymentStatus: "PENDING",
    paymentBadge: "Pending",
    orderStatus: "PENDING",
    date: "Sep 15, 2026",
    createdAt: "2026-09-15T09:00:00Z",
    amount: 1850,
    formattedAmount: "৳1,850",
  },
  {
    id: "ord-3",
    orderNumber: "#SD-4819",
    invoiceNo: "#SD-4819",
    customer: {
      id: "c3",
      name: "Kamal Hossain",
      email: "kamal.h@gmail.com",
      phone: null,
    },
    paymentStatus: "PAID",
    paymentBadge: "Paid",
    orderStatus: "COMPLETED",
    date: "Sep 14, 2026",
    createdAt: "2026-09-14T15:00:00Z",
    amount: 5400,
    formattedAmount: "৳5,400",
  },
  {
    id: "ord-4",
    orderNumber: "#SD-4818",
    invoiceNo: "#SD-4818",
    customer: {
      id: "c4",
      name: "Ridwana Islam",
      email: "ridwana@outlook.com",
      phone: null,
    },
    paymentStatus: "FAILED",
    paymentBadge: "Failed",
    orderStatus: "CANCELLED",
    date: "Sep 13, 2026",
    createdAt: "2026-09-13T12:00:00Z",
    amount: 990,
    formattedAmount: "৳990",
  },
  {
    id: "ord-5",
    orderNumber: "#SD-4817",
    invoiceNo: "#SD-4817",
    customer: {
      id: "c5",
      name: "Shafiul Bari",
      email: "shafiul@gmail.com",
      phone: null,
    },
    paymentStatus: "PAID",
    paymentBadge: "Paid",
    orderStatus: "COMPLETED",
    date: "Sep 12, 2026",
    createdAt: "2026-09-12T14:00:00Z",
    amount: 2650,
    formattedAmount: "৳2,650",
  },
];
